In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

# the scaler - for robust scaling
from sklearn.preprocessing import Normalizer

C:\ProgramData\anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
# load the California House price data from Scikit-learn
X, y = fetch_california_housing(return_X_y=True, as_frame=True)

# Remove 2 variables:
X.drop(labels=["Latitude", "Longitude"], axis=1, inplace=True)

# display top 5 rows
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467

In [3]:
# let's separate the data into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=0,
)

X_train.shape, X_test.shape

((14448, 6), (6192, 6))

In [4]:
# 以l1進行scaling
# set up the scaler
scaler = Normalizer(norm="l1")  # for euclidean distance we change to norm='l2'

# fit the scaler, this procedure does NOTHING
scaler.fit(X_train)

# transform train and test sets
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [5]:
# let's calculate the norm for each observation (feature vector)
# original data

np.round(np.linalg.norm(X_train, ord=1, axis=1), 1)

array([ 255.3,  889.1, 1421.7, ...,  744.6, 1099.5, 1048.9])

In [6]:
# let's calculate the norm for each observation (feature vector)
# scaled data

np.round(np.linalg.norm(X_train_scaled, ord=1, axis=1), 1)

array([1., 1., 1., ..., 1., 1., 1.])

In [7]:
## 以l2進行scaling
# set up the scaler
scaler = Normalizer(norm="l2")

# fit the scaler, this procedure does NOTHING
scaler.fit(X_train)

# transform train and test sets
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
# let's calculate the norm for each observation (feature vector)
# original data

np.round(np.linalg.norm(X_train, ord=2, axis=1), 1)

array([ 200. ,  837.1, 1387.1, ...,  704.7, 1052.6, 1024.1])

In [9]:
# let's calculate the norm for each observation (feature vector)
# scaled data

np.round(np.linalg.norm(X_train_scaled, ord=2, axis=1), 1)

array([1., 1., 1., ..., 1., 1., 1.])